#!/usr/bin/env bash

function run() {
  local project_path=$(pwd)
  local projectdir=$(_app_get_projectdir $project_path)
  local pathfile=$(_app_path_file $projectdir)
  [ -e $pathfile ] && echo "This directory is already registered as a project." && return

  mkdir -p $projectdir
  echo $project_path >> $pathfile
  _app_log_format 'Project initiated.' >> $(_app_log_file $projectdir)
  echo '@see HISTORY.log' >> $(_app_document_file $projectdir)
  git add $projectdir/
  git commit -m"Initiates project $project_path"
  _app_projectdir_touch $projectdir
}
