#!/usr/bin/env bash

function run() {
  local index=$(potato_get_arg 1)
  local datadir=$(_app_get_datadir)
  local projectdir=$(cat $datadir/dirs | uniq | tail -${index:-2} | head -1)
  local pathfile=$(_app_path_file $projectdir)
  [ -e $pathfile ] && [ -e "$(cat $pathfile)" ] && cd $(cat $pathfile) && bash || echo "Project not found at $projectdir" && return
}
