#!/usr/bin/env bash

function run() {
  local projectdir=$(_app_get_projectdir $(pwd))
  local logfile=$(_app_log_file $projectdir)
  _app_projectdir_touch $projectdir
  if [ ! -z "$(potato_get_arg 1)" ]; then
    # log user comment
    _app_log_format "$(potato_get_args)" >> $logfile
    git add $projectdir/
    git commit -m'Updates history for '$projectdir
  else
    # display current log
    less $logfile
  fi
}
