#!/usr/bin/env bash

function run() {
  local projectdir=$(_app_get_projectdir $(pwd))
  if [ -d $projectdir ]; then
    echo "This directory has been initiated. Run 'project ls' for more information"
  else
    echo "This directory is NOT registered as a project. Run 'project init'."
  fi
}
